version: '3.8'

services:
  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data

  fileserver:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - minio
      - db
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fileserver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  minio-data:
  postgres-data:
